# Spellcheck config
dev_comments = false
skip_readme = true 

[Hunspell]
lang = "en_US"
skip_os_lookups = true
use_builtin = true
search_dirs = ["."]
extra_dictionaries = [ "./local.dic" ]

[Hunspell.quirks]
transform_regex = ["^'([^\\s])'$", "^[0-9]+x$"]
allow_concatenation = true 
allow_dashed = false 

[Reflow]
max_line_length = 80
